In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
# 이상치 개수 세는 함수
def countOutliers(x, column):
    q1 = x[column].quantile(0.25)
    q3 = x[column].quantile(0.75)
    
    iqr = 1.5 * (q3 - q1)
 
    lenOutliers = len(x[column][(x[column] > (q3 + iqr)) | (x[column] < (q1 - iqr))])
    
    return lenOutliers

# 이상치 NaN으로 만드는 함수
def NaNOutliers(x, column):
    q1 = x[column].quantile(0.25)
    q3 = x[column].quantile(0.75)
    
    iqr = 1.5 * (q3 - q1)
 
    x[column][(x[column] > (q3 + iqr)) | (x[column] < (q1 - iqr))] = None
    
    return x[column]

In [ ]:
pre_review = pd.read_csv("C:/Users/taeroonie/빅데이터 최종 프로젝트/A반_3조_보험_Data Set/insu_pre_review.csv", encoding='euc-kr')
pre_review.head()

,customer_id,review_cat,judge,review_date,gender,age,height,weight,bust,waist,...,bt_mch_judge,bt_mchc_judge,bt_mvc_judge,bt_plat_judge,bt_rbc_judge,bt_wbc_judge,bt_rgpt_judge,bt_sgot_judge,bt_sgpt_judge,bt_trig_judge
0,C112346,혈액검사,재검,2014-10-09,1,70,165,63,92.0,88.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,C112350,일반검진,재검,2014-11-18,1,69,178,75,99.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C112355,일반검진,재검,2015-03-18,1,70,169,69,96.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,C112356,혈액검사,재검,2015-09-28,1,70,165,64,103.0,92.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,C112358,혈액검사,거절,2015-02-24,1,70,166,73,100.0,91.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
pre_review[pre_review['waist'].isna() == True]

,customer_id,review_cat,judge,review_date,gender,age,height,weight,bust,waist,...,bt_mch_judge,bt_mchc_judge,bt_mvc_judge,bt_plat_judge,bt_rbc_judge,bt_wbc_judge,bt_rgpt_judge,bt_sgot_judge,bt_sgpt_judge,bt_trig_judge
8951,C125485,혈액검사,승인,2015-07-22,2,54,165,82,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14864,C134121,일반검진,승인,2015-08-28,2,51,167,57,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
screen_nh = pd.read_excel("C:/Users/taeroonie/빅데이터 최종 프로젝트/A반_3조_보험_Data Set/insu_nh_n_screen(결측치제거).xlsx", sheet_name='Sheet1')
screen_nh.reset_index(drop=True, inplace=True)
screen_nh.head()

,no,gender,age_group,height_group,weight_group,waist,eyesight_left,eyesight_right,hearing_left,hearing_right,...,bt_trig,bt_hdl,bt_ldl,bt_mch,bt_crea,bt_ast,bt_alt,bt_rgpt,smoke_flag,drinking_flag
0,1,2,55~59,155,55,67.5,0.9,1.0,1,1,...,97,52,88,13.4,0.6,21,24,30,1,1
1,2,1,35~39,170,70,84.8,1.2,1.0,1,1,...,139,46,136,17.1,0.9,25,30,33,2,1
2,3,1,35~39,170,70,86.0,1.0,1.0,1,1,...,82,50,123,14.7,0.7,43,46,88,1,1
3,4,2,40~44,155,50,77.0,1.5,1.5,1,1,...,55,47,117,13.4,0.6,17,8,10,1,0
4,5,2,40~44,165,55,66.0,1.0,1.0,1,1,...,65,64,104,10.3,0.7,39,43,18,1,1

In [ ]:
screen_nh.groupby("weight_group")["waist"].agg("mean")

weight_group
25      62.333333
30      66.033929
35      63.742923
40      65.445805
45      68.524261
50      72.349001
55      76.254346
60      80.026030
65      83.219362
70      85.868214
75      88.374809
80      91.070935
85      93.965938
90      96.864200
95      99.598838
100    102.829759
105    105.699792
110    108.780992
115    112.299281
120    115.261062
125    116.872093
130    118.480000
135    123.916667
140    128.312500
145    129.500000
150    130.000000
175    123.000000
180    150.000000
Name: waist, dtype: float64

In [ ]:
pre_review.loc[8951,'waist'] = 91.070935
pre_review.loc[14864,'waist'] = 76.254346

In [ ]:
pre_review[pre_review['waist'].isna() == True]

Empty DataFrame
Columns: [customer_id, review_cat, judge, review_date, gender, age, height, weight, bust, waist, bp_min, bp_max, pulse_count, bt_chol, bt_crea, bt_gluc, bt_hb, bt_hbsa, bt_hct, bt_mch, bt_mchc, bt_mvc, bt_plat, bt_rbc, bt_wbc, bt_rgpt, bt_sgot, bt_sgpt, bt_trig, judge_score, bp_judge, pulse_count_judge, bt_chol_judge, bt_crea_judge, bt_gluc_judge, bt_hb_judge, bt_hbsa_judge, bt_hct_judge, bt_mch_judge, bt_mchc_judge, bt_mvc_judge, bt_plat_judge, bt_rbc_judge, bt_wbc_judge, bt_rgpt_judge, bt_sgot_judge, bt_sgpt_judge, bt_trig_judge]
Index: []

[0 rows x 48 columns]

In [ ]:
NaN_index = list(pre_review[pre_review["pulse_count"].isna()].index)
print(NaN_index)

[2895, 7898, 10961, 11188]

In [ ]:
pre_review.drop(NaN_index, inplace=True)

In [ ]:
pre_review[pre_review['pulse_count'].isna() == True]

Empty DataFrame
Columns: [customer_id, review_cat, judge, review_date, gender, age, height, weight, bust, waist, bp_min, bp_max, pulse_count, bt_chol, bt_crea, bt_gluc, bt_hb, bt_hbsa, bt_hct, bt_mch, bt_mchc, bt_mvc, bt_plat, bt_rbc, bt_wbc, bt_rgpt, bt_sgot, bt_sgpt, bt_trig, judge_score, bp_judge, pulse_count_judge, bt_chol_judge, bt_crea_judge, bt_gluc_judge, bt_hb_judge, bt_hbsa_judge, bt_hct_judge, bt_mch_judge, bt_mchc_judge, bt_mvc_judge, bt_plat_judge, bt_rbc_judge, bt_wbc_judge, bt_rgpt_judge, bt_sgot_judge, bt_sgpt_judge, bt_trig_judge]
Index: []

[0 rows x 48 columns]

In [ ]:
pre_review['bmi'] = (pre_review['weight'] / pre_review['height'] **2) * 10000

In [ ]:
pre_review.head()

,customer_id,review_cat,judge,review_date,gender,age,height,weight,bust,waist,...,bt_mchc_judge,bt_mvc_judge,bt_plat_judge,bt_rbc_judge,bt_wbc_judge,bt_rgpt_judge,bt_sgot_judge,bt_sgpt_judge,bt_trig_judge,bmi
0,C112346,혈액검사,재검,2014-10-09,1,70,165,63,92.0,88.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,23.140496
1,C112350,일반검진,재검,2014-11-18,1,69,178,75,99.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.671254
2,C112355,일반검진,재검,2015-03-18,1,70,169,69,96.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.158818
3,C112356,혈액검사,재검,2015-09-28,1,70,165,64,103.0,92.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.507805
4,C112358,혈액검사,거절,2015-02-24,1,70,166,73,100.0,91.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,26.491508

In [ ]:
pre_review['age'] =pre_review['age'] - (pre_review['age'] % 5)
pre_review['height'] =pre_review['height'] - (pre_review['height'] % 5)
pre_review['weight'] =pre_review['weight'] - (pre_review['weight'] % 5)

In [ ]:
pre_review.head()

,customer_id,review_cat,judge,review_date,gender,age,height,weight,bust,waist,...,bt_mchc_judge,bt_mvc_judge,bt_plat_judge,bt_rbc_judge,bt_wbc_judge,bt_rgpt_judge,bt_sgot_judge,bt_sgpt_judge,bt_trig_judge,bmi
0,C112346,혈액검사,재검,2014-10-09,1,70,165,60,92.0,88.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,23.140496
1,C112350,일반검진,재검,2014-11-18,1,65,175,75,99.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.671254
2,C112355,일반검진,재검,2015-03-18,1,70,165,65,96.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.158818
3,C112356,혈액검사,재검,2015-09-28,1,70,165,60,103.0,92.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.507805
4,C112358,혈액검사,거절,2015-02-24,1,70,165,70,100.0,91.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,26.491508

In [ ]:
((pre_review['gender']==1) & (pre_review['bmi'] >24.9) & (pre_review['waist'] >=90))

0        False
1        False
2        False
3        False
4         True
         ...
14933    False
14934    False
14935    False
14936    False
14937    False
Length: 14934, dtype: bool

In [ ]:
# # pre_review['bmi_waist'] = 
# if pre_review['gender'] ==1 & pre_review['bmi'] > 24.9 & pre_review['waist'] >=90:
#     np.where(pre_review['bmi_waist'],1,0)
# elif pre_review['gender'] == 0 & pre_review['bmi'] > 24.9 & pre_review['waist'] >=90:
pre_review['bmi_waist']=((pre_review['gender']==1) & (pre_review['bmi'] >24.9) & (pre_review['waist'] >=90))
pre_review['bmi_waist']

0        False
1        False
2        False
3        False
4         True
         ...
14933    False
14934    False
14935    False
14936    False
14937    False
Name: bmi_waist, Length: 14934, dtype: bool

In [ ]:
pre_review_True = pre_review[(pre_review['gender']==1) & (pre_review['bmi'] >24.9) & (pre_review['waist'] >=90)]
pre_review_True

,customer_id,review_cat,judge,review_date,gender,age,height,weight,bust,waist,...,bt_mvc_judge,bt_plat_judge,bt_rbc_judge,bt_wbc_judge,bt_rgpt_judge,bt_sgot_judge,bt_sgpt_judge,bt_trig_judge,bmi,bmi_waist
4,C112358,혈액검사,거절,2015-02-24,1,70,165,70,100.0,91.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,26.491508,True
7,C112365,일반검진,승인,2014-11-19,1,65,160,65,96.0,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.171875,True
16,C112380,일반검진,승인,2015-01-28,1,65,165,70,98.0,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.711662,True
23,C112391,혈액검사,재검,2015-07-06,1,65,175,85,106.0,95.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,27.440599,True
34,C112404,혈액검사,재검,2015-03-29,1,65,175,75,101.0,92.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.795918,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7014,C122645,혈액검사,승인,2014-11-20,1,50,170,80,102.0,90.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,26.423570,True
7026,C122669,혈액검사,거절,2014-12-09,1,35,170,85,104.0,90.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,30.449827,True
7041,C122698,일반검진,재검,2015-06-11,1,45,175,95,113.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.346939,True
14901,C134187,혈액검사,승인,2015-09-13,1,50,170,80,98.0,94.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,26.729927,True
14902,C134188,일반검진,승인,2015-06-22,1,40,175,75,100.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.469388,True

In [ ]:
pre_review['bmi_waist_judge'] = 1

In [ ]:
bmi_waist

NameError: name 'bmi_waist' is not defined

In [ ]:
# pre_review.to_excel("C:/Users/taeroonie/빅데이터 최종 프로젝트/A반_3조_보험_Data Set/insu_pre_review_processing.xlsx", index=False, encoding='utf-8')